set_property PACKAGE_PIN AA8 [get_ports {gpio_tri_o[3]}]
set_property PACKAGE_PIN AB9 [get_ports {gpio_tri_o[2]}]
set_property PACKAGE_PIN AB11 [get_ports {gpio_tri_o[0]}]
set_property PACKAGE_PIN AB10 [get_ports {gpio_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_o[0]}]